version: '3.9'

services:
  mongo:
    image: mongo:5.0.31-rc0-focal
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./scripts/docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - wireguard-api-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - wireguard-api-network

  wireguard-api:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ${PEERS_RESOURCE_PATH}:/etc/wireguard
      - ${API_SECRET_PATH}:/etc/secret
    environment:
      - API_SECRET_KEY=${API_SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
      - API_SECRET_AUTHORIZATION=${API_SECRET_AUTHORIZATION}
    restart: always
    depends_on:
      - mongo
    networks:
      - wireguard-api-network

volumes:
  wireguard-api-mongo-data:

networks:
  wireguard-api-network:
    driver: bridge
