name: Build Validation

on:
  push:
    branches:
      - "*"

jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compilation Check
        run: |
          make compile


