name: Build Validation

on:
  push:
    branches:
      - "*"

jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/checkout@v4
        run: |
          make compile


